### ISSUE TITLE
CsharpGL for UWP 

### ISSUE THREAD

**Issue by JimSEOW** [bitzhuwei/CSharpGL#13]
do you have plan to make CsharpGL works in UWP?

For example
https://github.com/luca-piccioni/OpenGL.Net
With mapping to OpenGL of [ANGLE](https://github.com/Microsoft/angle) 

ANGLE(OpenGL) in UWP [C++](http://developernote.com/2015/11/combining-opengl-and-xaml-together-in-a-windows-store-app-uwp/ )

ANGLE(OpenGL) in UWP [c#](http://www.instructables.com/id/C-OpenGL-ES-Viewer-in-C/step2/Get-ANGLE/)

**Comment by bitzhuwei** [comment]
Sorry I don't have plans for UWP or .NET Core recently. Now I'm trying to integrate more comon or useful functions/features into CSharpGL. I think there will be other developers help me make CSharpGL work in UWP in the future.

**Comment by zwcloud** [comment]
@JimSEOW [CSharpGL.Core](https://github.com/zwcloud/CSharpGL.Core) is working on .NET Core. I'm using that in my .NET Core project. All dependencies to Winform is removed. An older version works on .NET 4.5 with only two denpendencies: `System` and `System.Core`.
The content of CSharpGL.Core is not in sync with this main project. I will do that later.
