### ISSUE TITLE
SimpleObjLoader doesn't show wavefront for me.

### ISSUE THREAD

**Issue by sourceskyboxer** [bitzhuwei/CSharpGL#133]
I have tried to load obj but it doesn't see in WinControlGL.

But it is nicd because you have made with OrderIndependentTransparency and it loads for my computer black surface of wavefront obj. Does it happen?

Thanks for fixing!

PS nice your Wavefront loader works fine than OpenTK. How did you resolve that? I already tried since March 2018 with custom wavefront loader with OpenTK.  And it doesn't work for me. I cancelled my work with C# OpenTK. I see that your framework CSharpGL has another structures.

Thanks and sorry for bad English! I can't speak good for Japanese/Chinese.

**Comment by bitzhuwei** [comment]
1. Have you tried the 'Demos\SimpleObjFile' project? did you see this below?
[nanosuit](https://github.com/bitzhuwei/CSharpGL/blob/master/Demos/SimpleObjFile/nanosuit.png?raw=true)
If you can not see this, please email me your obj file and let me try to solve it.
2. The ‘OrderIndependentTransparency‘ project requires GLSL version 420. Please make sure your graphics card drive meets the version requirement.
3. I take steps to parse the obj file format. You can see there are multiple small parser types in [PartParsers](https://github.com/bitzhuwei/CSharpGL/tree/master/Infrastructure/CSharpGL.Models/SimpleObjFileFormat/PartParsers) folder. Each of them do something simple. And all of them work together to finally provide a structured obj data for rendering.
I'm Chinese. Hope you like this project!
