### ISSUE TITLE
3ds ChunkBase 模块在哪里？

### ISSUE THREAD

**Issue by litterbug23** [bitzhuwei/CSharpGL#148]
3ds ChunkBase 模块在哪里？

**Comment by bitzhuwei** [comment]
@litterbug23 https://github.com/bitzhuwei/CSharpGL2/blob/d164bf4042df343d7de157c3f19df801c35edf12/Functions/FileParsers/CSharpGL.FileParser._3DSParser/Chunks/ChunkBase.cs
