### ISSUE TITLE
RaycastVolumeRenderer not working

### ISSUE THREAD

**Issue by JimSEOW** [bitzhuwei/CSharpGL#15]
DemoRendererFactory: RaycastVolumeRenderer  produces blank, no loading of head256.raw

**Comment by bitzhuwei** [comment]
I'm not sure, but maybe it's requires a newer graphics card drive. Update your graphics card drive and try again.
![raycast-volume-rendering](https://github.com/bitzhuwei/CSharpGL/raw/gh-pages/images/CSharpGL/raycast-volume-render.gif?raw=true)

**Comment by JimSEOW** [comment]
my graphics card 860M is up to date with the latest Nvidia driver
![2016-10-14_12-09-02](https://cloud.githubusercontent.com/assets/8244633/19383936/13c21002-9207-11e6-92bf-b1782b4eaa52.gif)

**Comment by bitzhuwei** [comment]
That's not the latest version of CSharpGL. Now 23 is 'Single Renderer'. 'Form10RaycastVolumeRender' is already removed because the 'RaycastVolumeRenderer' is moved into 'Single Renderer'.
![single renderer](http://images.cnblogs.com/cnblogs_com/bitzhuwei/895194/o_1.png)
