### ISSUE TITLE
English docs

### ISSUE THREAD

**Issue by sodalom** [bitzhuwei/CSharpGL#170]
Hi, this project looks interesting and I would like to try out. Is there is English documentation available?

**Comment by bitzhuwei** [comment]
The only 'documentation' is demo projects in https://github.com/bitzhuwei/CSharpGL/tree/master/Demos and https://github.com/bitzhuwei/CSharpGL/tree/master/Demos.
I have a new book published, but it's in Chinese.

**Comment by sodalom** [comment]
Thanks. This will help for now, but hopefully one day there will be English docs!
