### ISSUE TITLE
ImageProcessing.GrayFilter demo memory leak?

### ISSUE THREAD

**Issue by sheiling** [bitzhuwei/CSharpGL#172]
Hi zhuwei,this project is very usefully to my project! but I also have some problems about CSharpGL. 
When I load image more twice of times in ImageProcessing.GrayFilter demo, the memory rise to a bigger number. A large image will make this issue in a easy way(my test image of 7MB).

**Comment by bitzhuwei** [comment]
Thank you for your praise. The bigger number of memory usage is not necessarily a memory leak. Please try to use `GC.Colloct()` to check if memory goes lower. Or, check other demos that involve `Texture` and images to see if they also occupy larger memory. 
If the problem is somewhere inside the CSharpGL project, please let me know so that I could fix it.
Thank you.

**Comment by sheiling** [comment]
Thanks for answer. But in a old computer (with machine meory is 4GB), could using almost of memory......
Just do this test:
![image](https://user-images.githubusercontent.com/15042542/69771304-575b8080-11c7-11ea-85cd-910618721eac.png)
My project update texture coordinate realtime. 
This is my test image(have 7MB):
![星空](https://user-images.githubusercontent.com/15042542/69771425-b7522700-11c7-11ea-945d-66d5b4515fe7.jpg)
Thanks!

**Comment by bitzhuwei** [comment]
Does `My project update texture coordinate realtime.` mean that you have to update texture every frame?

**Comment by sheiling** [comment]
this way is so poor,this is  my fault! 
Some times could update images (with have some width and height). 
but I cannot find a proper example in Demo.  
_update texture coordinate realtime._ is not a suitable way.

**Comment by sheiling** [comment]
My project is like some projector mapping. like some of this video, it will update realtime.
https://vimeo.com/244396874
https://github.com/kasparsj/ofxpimapper-tree

**Comment by bitzhuwei** [comment]
Unfortunately the video link gave me an `ERR_CONNECTION_TIMED_OUT` error.

**Comment by sheiling** [comment]
Could test this issus will help me directly.

> Thanks for answer. But in a old computer (with machine meory is 4GB), could using almost of memory......
> Just do this test:
> ![image](https://user-images.githubusercontent.com/15042542/69771304-575b8080-11c7-11ea-85cd-910618721eac.png)
> My project update texture coordinate realtime.
> This is my test image(have 7MB):
> ![星空](https://user-images.githubusercontent.com/15042542/69771425-b7522700-11c7-11ea-945d-66d5b4515fe7.jpg)
> Thanks!

**Comment by bitzhuwei** [comment]
Sorry I don't feel obligated to test that.

**Comment by sheiling** [comment]
may be make a false choice. The opentk will be only choice.
