### ISSUE TITLE
OrderIndependentTransparentcy 的例子运行为黑色

### ISSUE THREAD

**Issue by DengCun** [bitzhuwei/CSharpGL#173]
OrderIndependentTransparentcy 的例子运行为黑色，问一下是什么问题？

**Comment by bitzhuwei** [comment]
请详述你的问题。遇到何种exception? 各参数为何？

**Comment by DengCun** [comment]
我下载完项目后直接用vs2017运行OIT例子，程序运行成功没有报任何exception，但是茶壶是黑色的

**Comment by bitzhuwei** [comment]
试试更新显卡

**Comment by DengCun** [comment]
我使用的是 NVIDIA GeForce GT 720 25.21.14.1881版本的显卡，已经是最新的了

**Comment by bitzhuwei** [comment]
试试更新显卡驱动，再搜索看看有没有log文件

**Comment by DengCun** [comment]
在OIT例子里面
第一次渲染的时候
`      private const string buildListsFrag = @"#version 420 core

layout (early_fragment_tests) in;

layout (binding = 0, offset = 0) uniform atomic_uint atomicCounter;
layout (binding = 0, r32ui) uniform uimage2D heads;
layout (binding = 1, rgba32ui) uniform writeonly uimageBuffer lstBuffer;

in vec4 passColor;

layout (location = 0) out vec4 color;

void main(void)
{
    uint index;
    uint old_head;
    uvec4 item;

    index = atomicCounterIncrement(atomicCounter);

    **old_head = imageAtomicExchange(heads, ivec2(gl_FragCoord.xy), uint(index));**

    item.x = old_head;
    item.y = packUnorm4x8(passColor);
    item.z = floatBitsToUint(gl_FragCoord.z);
	item.w = 255 / 4;

    imageStore(lstBuffer, int(index), item);

    //color = passColor;
	discard;
}`
第二次渲染的时候 
`void main(void)
{
    uint current_index;
    uint fragment_count = 0;

    **current_index = imageLoad(heads, ivec2(gl_FragCoord).xy).x;**
    while (current_index != 0 && fragment_count < MAX_FRAGMENTS)
    {
        uvec4 fragment = imageLoad(lstBuffer, int(current_index));
        fragment_list[fragment_count] = fragment;
        current_index = fragment.x;
        fragment_count++;
    }

	if (fragment_count > 1)
	{
		for (uint i = 0; i < fragment_count - 1; i++)
		{
			uint p = i;
			uint depth1 = (fragment_list[p].z);
			for (uint j = i + 1; j < fragment_count; j++)
			{
				uint depth2 = (fragment_list[j].z);
				if (depth1 < depth2)
				{
					p = j; depth1 = depth2;
				}
			}
			if (p != i)
			{
				uvec4 tmp = fragment_list[p];
				fragment_list[p] = fragment_list[i];
				fragment_list[i] = tmp;
			}
		}
	}

    vec4 final_color = vec4(0.0);

    for (uint i = 0; i < fragment_count; i++)
    {
        vec4 modulator = unpackUnorm4x8(fragment_list[i].y);
        final_color = mix(final_color, modulator, modulator.a);
		final_color = final_color * (1.0f - modulator.a) + modulator * modulator.a;
    }

    color = final_color;

    // color = vec4(float(fragment_count) / float(MAX_FRAGMENTS));
}`
current_index 只是等于了imageLoad返回的vec4的x值，这样是不是有问题？难到不会导致current_index 永远为0，然后后面的while循环和for都不会执行，然后最终颜色就都是final_color的初始值0.0吗？

**Comment by bitzhuwei** [comment]
不会啊。你试下输出current_index为颜色，看看他是不是纯黑？

**Comment by DengCun** [comment]
这个我试过了，是黑色的

**Comment by DengCun** [comment]
您那 有您能运行成果的例子吗？有的话 发给我，如果还不能运行就说明是我电脑问题了。
邮箱972493523@qq.com

**Comment by bitzhuwei** [comment]
并没有。你试试从零开始抄这个例子的代码，看看抄到哪一步时会出现不正常的情况？或者试试一点点的削减代码，从削减shader开始
