### ISSUE TITLE
导入obj文件出错

### ISSUE THREAD

**Issue by iamweixiaohang** [bitzhuwei/CSharpGL#86]
你好，最近在学习OpenGL，由于做过C#的项目，所以还想使用C#，然后看到了你的教程，接着跑了几个例程，我发现只有用你给的nanosuit.obj文件才能渲染出图，自己的obj文件一直提示错误，所以想问一下，这是怎么回事？是我的格式不对吗？

**Comment by bitzhuwei** [comment]
我些的obj解析器不能解析所有的obj文件。多找几个obj试试。
